server:
  port: 9000

spring:
  application:
    name: mobility-hub-backend

  sql:
    init:
      encoding: UTF-8
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mobilityhub?serverTimezone=Asia/Seoul
    username: sample
    password: 1234
  mqtt:
    url: tcp://192.168.35.183:1883 # 브로커 주소
    #    username: myUser             # (선택) 계정
    #    password: myPassword         # (선택) 비밀번호
    client-id: spring-boot-app # 기본 클라이언트 ID

    # 토픽 설정
    topic:
      command: server/command # 발행(Publish)할 토픽
      sensor: mobility/hub/car/status # 구독(Subscribe)할 토픽

  jpa:
    show-sql: true #JPA가 생성하는 sql문을 콘솔에 보여준다
    hibernate:
      ddl-auto:
        none
        # ddl-auto: create #서버가 시작되면 create문이 실행된다 - 데이터가 있어도 삭제하고 만든다
    # ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  secret: c3ByaW5nc2VjdXJpdHktand0LXJlYWN0LXRlc3QtbXF0dC1yYXNwYmVycnlwaQ==
  token-valid-in-second: 3600000
