server:
  port: 9000


spring:
  application:
    name: mobility-hub-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mobilityhub?serverTimezone=Asia/Seoul
    username: sample
    password: 1234



  jpa:
    show-sql: true #JPA가 생성하는 sql문을 콘솔에 보여준다
    hibernate:
      ddl-auto: none
#      ddl-auto: create #서버가 시작되면 create문이 실행된다 - 데이터가 있어도 삭제하고 만든다
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

    jwt:
      header: Authorization
      secret: c3ByaW5nc2VjdXJpdHktand0LXJlYWN0LXRlc3QtbXF0dC1yYXNwYmVycnlwaQ==
      token-valid-in-second: 3600000

